apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld1
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld1
    spec:
      containers:
      - name: helloworld1
        image: quay.io/weaveworks/helloworld:master-9a16ff945b9e
        args:
        - -msg=GOODDAY6
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
